- name: variables at task level
  hosts: localhost
  # these variables are at parent or play level
  vars:
  - money: "100 RS"
    land: "100 acrs"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add and override
    vars:
    - money: "200 RS"
      houses: "3 houses"
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"
  
