- name: testing variable precedence
  hosts: mongodb
  # vars:
  #   NAME: Sai-play
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: USERNAME
  #   prompt: Please enter the tariner name
  #   private: false
  tasks:
  - name: variable at task level
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"

      
      #ouputs preferences

      # 1. first prefrerence is command line
      # 2. task level
      # 3.vars_files
      #4. prompt
      #5.play-level


