- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # this command is user whenever you want ot run linux commands directly 
    # i .e in the case ansible module not available no gurenteee that all commands available in linuc in that case we need to give the commands directly
     ansible.builtin.shell: cat /etc/motd 
     register: output # out put is variable name
  - name: print the command output
    ansible.builtin.debug:
    msg: "output is: {{output}}" 
  