- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # this command is user whenever you want ot run linux commands directly 
    # i .e in the case ansible module not available no gurenteee that all commands available in linuc in that case we need to give the commands directly
    # when the user does not exist ansible treating this as failure ans comeout by default
    # noe we want to ignore the failure
    #ignore_errors: true

    ansible.builtin.shell: id roboshop 
    register: output # out put is variable name
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
     msg: "output is: {{output}}" 

  - name: print exist status
    ansible.builtin.debug:
     msg: "output is: {{output.rc}}"

  - name: create user roboshop
    ansible.builtin.debug:
     msg: roboshop
    when: output.rc !=0