- name: loops example
  hosts: localhost # you no need to give user name and password 
  tasks: 
  - name: print the names
    ansible.builtin.debug:
     msg: "Hello {{item}}"
    loop:
    - sai
    - ramesh
    - suresh