- name: install packages
  hosts: localhsost
  become: yes
  tasks:
  - name: install pacakages
    ansible.builtin.debug:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - postmap 