- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install pacakages
    ansible.builtin.debug:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx