- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: "{{item.name}}"
     state: "{{item.state}}"
     # list of string
    # loop:
    # - nginx
    # - postfix
    # - cyrus-sasl-plain
    # - mailx
     # list of map
    loop:
    - {name: 'nginx', state: 'absent'} 
    - {name: 'postfix', state: 'installed'}
    - {name: 'cyrus-sasl-plain', state: 'absent'}
    - {name: 'mailx', state: 'installed'}